### ISSUE TITLE
HTTP 299 response causing error when attempting to parse the response

### ISSUE THREAD

**Issue by babakontheweb** [smarty/smartystreets-javascript-sdk#100]
We recently came across an error with our integration with this SDK where a `POST` to `https://us-street.api.smarty.com/street-address` responded with an unexpected status code HTTP 299. With the status code being a 2xx class, the SDK then attempted to parse the response only to fail with the following message and trace.

```
response.payload.map is not a function
TypeError: response.payload.map is not a function
    at assignResultsToLookups (util/sendBatch.js:30:20)
    at util/sendBatch.js:18:13
    at process.processTicksAndRejections (process/task_queues:95:5)
```

<img width="562" alt="Screenshot 2024-12-19 at 3 38 37 PM" src="https://github.com/user-attachments/assets/e761e37f-3ecd-4233-ab6d-20e538d1046a" />

This was on version 5.1.1 of the SDK but reviewing the [latest version of assignResultstoLookups](https://github.com/smarty/smartystreets-javascript-sdk/blob/master/src/util/sendBatch.js#L29-L37) the same issue should occur with the latest version.

**Comment by maxwellpothier** [comment]
@babakontheweb is this still an active issue for you?
We had a few problems with a data center giving us `299` errors back in December, around the time this issue was logged. Because it's such a niche status code, I'm assuming this was part of that. If not, we'll take a deeper look!

**Comment by maxwellpothier** [comment]
I was able to find an incident report for when this occured
https://status.smarty.com/incidents/psz9nkbp7wfl
